#!/bin/bash

progress-bar() {
  local duration=${1}


    already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇▇"; done }
    remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf "  "; done }
    percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
    clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  clean_line
}

echo -e "\n\033[38;5;69mWelcome to Linter Tool, version 0.0.1! \n\033[0m"
echo -e "\033[38;5;229m# Searching for a project\033[0m"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
sleep .4
echo -e "Found project: $DIR/App/Solar System.xcodeproj\n"

echo -e "\033[38;5;229m# Gathering linter rules from configuration file\033[0m"
sleep 2s
echo -e "Found 168 rules to apply\n"

echo -e "\033[38;5;229m# Searching through Swift files in project\033[0m"

sleep 1s

echo -e "Found 50 Swift files\n"

echo -e "\033[38;5;229m# Executing rules against source files...\n\033[0m"

progress-bar 10

echo -e "\033[38;5;69mExecution finished.             \033[0m"
echo -e "\033[38;5;69mLinting took 11.61s.\033[0m"

sleep .4

echo -e "Report written to linter-report.json\n"